#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

$doc = <<<DOC
gendiff -h

Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOC;


$args = Docopt::handle(
    $doc,
    [
        'argv' => array_slice($_SERVER['argv'], 1),
        'help' => true,
        'version' => '0.1',
    ]
);

$diff = \Differ\Differ\genDiff($args->args['<firstFile>'], $args->args['<secondFile>']);

print_r($diff);
